name: nasa_apod_app
description: NASA APOD Explorer
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.6.1
  http: ^1.6.0
  flutter_secure_storage: ^10.0.0
  cached_network_image: ^3.4.1
  flutter_cache_manager: ^3.4.1
  photo_view: ^0.15.0
  video_player: ^2.11.1
  webview_flutter_platform_interface: ^2.14.0
  youtube_player_iframe: ^5.2.2
  url_launcher: ^6.3.2
  shared_preferences: ^2.5.5
  gal: ^2.3.2
  google_fonts: ^8.1.0
  wakelock_plus: ^1.4.0
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: true
  ios: false
  image_path: assets/branding/app_icon.png
  min_sdk_android: 21
  adaptive_icon_background: "#050A23"
  adaptive_icon_foreground: assets/branding/app_icon_foreground.png
  windows:
    generate: true
    image_path: assets/branding/app_icon.png
    icon_size: 256
